# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!


def pods_toInstall

# Pods for anITa
pod 'Alamofire', '4.4.0'

pod 'ObjectMapper' , '2.2.7'

pod 'AlamofireActivityLogger', '2.3.0' #to verify and remove

pod 'Signals', '4.0.0'

pod 'SwiftyBeaver', '1.2.2'

pod 'Kingfisher', '3.10.1'

pod 'SwiftyJSON' , '3.1.4'


end

target 'LearniatStudent' do
pods_toInstall
end

