# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.36.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    
    
  end

    desc "Builds development target and uploads to HockeyApp"
        lane :Hockey_Distributiion do
            build_number = increment_build_number
            version = get_version_number(xcodeproj: "LearniatTeacher.xcodeproj")
            update_info_plist( # Change the Display Name of your app
                              plist_path: "LearniatTeacher.xcodeproj/../LearniatTeacher/Info.plist",
                              display_name:"D."+version+"."+build_number)
        #Creating container of xcode project
        gym(
            configuration: "Development",
            scheme: "Development",
            silent: true,
            clean: true,
            export_method: "ad-hoc"
        )
        # Push to Hockey
        markdown_type = 1
        release_notes = "test hockey app"
        hockey(api_token:"af160cec3d0c4ec094c9f8a018cc33cf")
        end
  
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded. 
# Learn more at https://github.com/fastlane/fastlane#metrics
